apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.http]
        address = ":80"
 
      [entryPoints.https]
        address = ":443"

      [entryPoints.traefik]
        address = ":8080"

    [log]
      level = "DEBUG"

    [accessLog]

    [serversTransport]
      insecureSkipVerify = true

    [api]
      dashboard = true
      insecure = true

    [providers.file]
      filename = "/config/dynamic-conf.toml"
    
    [ping]

    [providers.kubernetesIngress]

    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]

    #[tracing]
    #  [tracing.jaeger]
    #    samplingServerURL = "http://192.168.15.139:5778/sampling"
    #    localAgentHostPort = "192.168.15.139:6831"
    #  [tracing.jaeger.collector]
    #    endpoint = "http://192.168.15.139:14268/api/traces?format=jaeger.thrift"

  dynamic-conf.toml: |
    [http.routers.api]
      rule = "Host(`traefik.192.168.15.16.nip.io`)"
      entrypoints = ["http"]
      service = "api@internal"

