apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: testheader-add
  namespace: kube-system
spec:
  headers:
    customRequestHeaders:
      X-Script-Name: "test"
    customResponseHeaders:
      X-Custom-Response-Header: "value"
