apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.web]
        address = ":80"
 
      [entryPoints.web-secure]
        address = ":443"

    [log]
      level = "DEBUG"

    [accessLog]

    [serversTransport]
      insecureSkipVerify = true

    [api]
      insecure = true

    [ping]

    [providers.kubernetesCRD]

    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]

    #[tracing]
    #  [tracing.jaeger]
    #    samplingServerURL = "http://192.168.15.139:5778/sampling"
    #    localAgentHostPort = "192.168.15.139:6831"
    #  [tracing.jaeger.collector]
    #    endpoint = "http://192.168.15.139:14268/api/traces?format=jaeger.thrift"
