apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik.192.168.15.16.nip.io`)
    kind: Rule
    services:
    - name: traefik-ingress-service
      port: 8080
    middlewares:
      - name: testheader-add

